DROP TABLE SERIES CASCADE CONSTRAINTS;
CREATE TABLE SERIES (
  TITRES  VARCHAR2(20),
  ANNEE   NUMBER(4),
  PAYS    VARCHAR2(10),
  NB_SAIS NUMBER,
  CONSTRAINT pk_series PRIMARY KEY (TITRES,ANNEE)
);

DROP TABLE GENRES CASCADE CONSTRAINTS;
CREATE TABLE GENRES(
  NOMG  VARCHAR2(20),
  CONSTRAINT pk_genre PRIMARY KEY (NOMG)
);

DROP TABLE TYPE CASCADE CONSTRAINTS;
CREATE TABLE TYPE(
  TITRES  VARCHAR2(20),
  ANNEE   NUMBER(4),
  NOMG    VARCHAR2(20),
  CONSTRAINT pk_type PRIMARY KEY(TITRES,ANNEE,NOMG)
);

DROP TABLE PERSONNES CASCADE CONSTRAINTS;
CREATE TABLE PERSONNES(
  PRENOM     VARCHAR2(15),
  NOM  VARCHAR2(15),
  PAYS_ORIGINE    VARCHAR2(20),
  CONSTRAINT pk_personnes PRIMARY KEY(NOM,PRENOM)
);

DROP TABLE CREER CASCADE CONSTRAINTS;
CREATE TABLE CREER(
  TITRES    VARCHAR2(20),
  ANNEE     NUMBER(4),
  PRENOM       VARCHAR2(15),
  NOM    VARCHAR2(15),
  DATE_CREAT    DATE,
  CONSTRAINT pk_creer PRIMARY KEY(TITRES,ANNEE,NOM,PRENOM)
);


DROP TABLE PRODUIRE CASCADE CONSTRAINTS;
CREATE TABLE PRODUIRE(
  TITRES    VARCHAR2(20),
  ANNEE     NUMBER(4),
  PRENOM       VARCHAR2(15),
  NOM    VARCHAR2(15),
  CONSTRAINT pk_produire PRIMARY KEY(TITRES,ANNEE,NOM,PRENOM)
);

DROP TABLE SAISONS CASCADE CONSTRAINTS;
CREATE TABLE SAISONS(
  ID_SAIS     VARCHAR2(15),
  NB_EPIS     NUMBER,
  TITRES      VARCHAR2(20),
  ANNEE       NUMBER(4),
  CONSTRAINT pk_saison PRIMARY KEY (ID_SAIS),
  CONSTRAINT fg_sais_seri FOREIGN KEY (TITRES,ANNEE) REFERENCES SERIES
);

DROP TABLE EPISODES CASCADE CONSTRAINTS;
CREATE TABLE EPISODES(
  TITREE    VARCHAR2(20),
  DUREE     NUMBER,
  DATE_P_D  DATE,
  RESUME    VARCHAR2(200),
  ID_SAIS   VARCHAR2(15),
  CONSTRAINT pk_episodes  PRIMARY KEY (TITREE),
  CONSTRAINT fg_epi_saison FOREIGN KEY (ID_SAIS) REFERENCES SAISONS
);

DROP TABLE JOUER CASCADE CONSTRAINTS;
CREATE TABLE JOUER(
  TITREE    VARCHAR2(15),
  PRENOM       VARCHAR2(15),
  NOM    VARCHAR2(15),
  CONSTRAINT pk_jouer PRIMARY KEY(TITREE,NOM,PRENOM)
);

DROP TABLE REALISER CASCADE CONSTRAINTS;
CREATE TABLE REALISER(
  TITREE    VARCHAR2(15),
  PRENOM       VARCHAR2(15),
  NOM    VARCHAR2(15),
  CONSTRAINT pk_realiser PRIMARY KEY(TITREE,NOM,PRENOM)
);

DROP TABLE UTILISATEURS CASCADE CONSTRAINTS;
CREATE TABLE UTILISATEURS(
  PSEUDO      VARCHAR2(10),
  DATE_INSC   DATE,
  AGE         NUMBER(2),
  SEXE        CHAR,
  CONSTRAINT pk_utilisateurs PRIMARY KEY (PSEUDO),
  CONSTRAINT ck_age_utili CHECK (AGE>=18),
  CONSTRAINT ck_sexe CHECK (SEXE='M' OR SEXE='F')
);

DROP TABLE NOTER_EPI CASCADE CONSTRAINTS;
CREATE TABLE NOTER_EPI(
  PSEUDO      VARCHAR2(10),
  TITREE      VARCHAR2(15),
  NOTE        NUMBER,
  COMMENTAIRE VARCHAR2(50),
  DATE_NO        DATE,
  CONSTRAINT pk_noter_epi PRIMARY KEY (PSEUDO,TITREE),
  CONSTRAINT ck_note_epis CHECK (NOTE >=0 AND NOTE <=10)
);

DROP TABLE NOTER_SER CASCADE CONSTRAINTS;
CREATE TABLE NOTER_SER(
  PSEUDO      VARCHAR2(10),
  TITRES      VARCHAR2(20),
  ANNEE       NUMBER(4),
  NOTE        NUMBER,
  COMMENTAIRE VARCHAR2(500),
  DATE_NO        DATE,
  CONSTRAINT pk_noter_ser PRIMARY KEY (PSEUDO,TITRES,ANNEE),
  CONSTRAINT ck_note_seri CHECK (NOTE >=0 AND NOTE <=10)
);

DROP TABLE MESSAGES CASCADE CONSTRAINTS;
CREATE TABLE MESSAGES(
  ID        NUMBER,
  TITRE     VARCHAR2(10),
  TEXTE     VARCHAR2(70),
  PSEUDO    VARCHAR2(10),
  DATE_ME      DATE,
  CONSTRAINT pk_messages PRIMARY KEY (ID),
  CONSTRAINT fg_messag_utili FOREIGN KEY (PSEUDO) REFERENCES UTILISATEURS
);

DROP TABLE REPONSE CASCADE CONSTRAINTS;
CREATE TABLE REPONSE(
  ID_R      NUMBER,
  TEXTE     VARCHAR2(70),
  ID        NUMBER,
  PSEUDO    VARCHAR2(10),
  DATE_RE    DATE,
  CONSTRAINT pk_reponse PRIMARY KEY (ID_R),
  CONSTRAINT fg_repon_mess FOREIGN KEY (ID) REFERENCES MESSAGES,
  CONSTRAINT fg_repon_utili FOREIGN KEY (PSEUDO) REFERENCES UTILISATEURS
);

DROP TABLE ASSOCIER CASCADE CONSTRAINTS;
CREATE TABLE ASSOCIER(
  ID        NUMBER,
  TITRES    VARCHAR2(10),
  ANNEE     NUMBER(4),
  CONSTRAINT pk_assoocier  PRIMARY KEY (ID,TITRES,ANNEE)
);
